services:
  filegator:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "888:8080" # frontend port, see package.json
      - "881:8081" # backend port, see package.json and .env.local
    extra_hosts:
      - "ldap.example.org:host-gateway"
      - "seaweed:host-gateway"
    volumes:
      # mount code:
      - ./frontend:/var/www/filegator/frontend
      - ./backend:/var/www/filegator/backend
      - ./repository:/var/www/filegator/repository
      # mount custom configuration (create configuration.php file first):
      - ./configuration.php:/var/www/filegator/configuration.php
      # mount php dependencies locally:
      #- ./vendor:/var/www/filegator/vendor
      #- ./composer.json:/var/www/filegator/composer.json
      #- ./composer.lock:/var/www/filegator/composer.lock
      # mount node dependencies locally:
      #- ./node_modules:/var/www/filegator/node_modules
      #- ./package.json:/var/www/filegator/package.json
      #- ./package-lock.json:/var/www/filegator/package-lock.json