services:
  filegator:
    build: .
    image: filegator:latest
    restart: always
    ports:
      - "2222:2222"
      - "2223:2223" # backend port, see package.json and .env.local
    volumes:
      - repository:/var/www/filegator/repository
      - private:/var/www/filegator/private
      - ./configuration.php:/var/www/filegator/configuration.php
    extra_hosts:
      - "ldap.example.org:host-gateway"
      - "seaweed:host-gateway"
      - "bucket-1.seaweed:host-gateway"

volumes:
  repository:
  private:
